### ISSUE TITLE
Log file of notify-by-ses

### ISSUE THREAD

**Issue by unaisarakkal** [npm/notify-by-ses#1]
I have configured this on within a nagios configuration on centos. May I know where should I find the log of this application as I have a confusion;

 pager                                    {{nagios_admin_email}}

Can I change pager -> email and  {{nagios_admin_email}} -> me@mydomain.com

**Comment by unaisarakkal** [comment]
Also I am not sure about whether notify-by-ses can be configured on a standard nagios set up

**Comment by bcoe** [comment]
Hello @unaisarakkal, the sample file in README.md is taken from our ansible-nagios scripts:

https://github.com/npm/ansible-nagios/blob/master/templates/ses_nagios.cfg.j2

All variables in `{{`, `}}`, should be replaced with appropriate variables when you deploy the notifier. Another option, if you're able to deploy on Ubuntu, would be using our open-source `ansible-nagios` repo.
